### ISSUE TITLE
Getting no TypeScript error in swap

### ISSUE THREAD

**Issue by soeik** [derrickbeining/react-atom#55]
Hi!

Thank you for maintaining such a good lib! I wondered if somebody implemented something like an atom in Clojure and I'm here!

**UPD:** 
Probably I should address this question to @libre/atom, but I'll leave it here for now.

I'm playing with it and thinking about using it in my TypeScript project but I'm curious why I'm not receiving any TS error when trying to swap state to something, that doesn't match its initial shape. 
For example:

```
export interface AppState {
    isLoading: Boolean
}

export const appState = Atom.of<AppState>({
    isLoading: false,
})

export const setIsLoading = (isLoading: boolean) =>
    swap<AppState>(appState, (state) => ({
        ...state,
        foo: 0, // No error here
        isLoading,
    }))
```

Am I doing something wrong?

Thank you in advance!

**Comment by derrickbeining** [comment]
@soeik my apologies for not seeing this sooner. No I don't think you're doing anything wrong. This is just the way TypeScript handles excess property checking. Here's a decent [article](https://medium.com/@lemoine.benoit/why-does-typescript-sometimes-fails-to-type-check-extra-properties-fd230ebbc295) on the subject. If you want to get a type error, you'd need to specifically annotate the return type of the update function in `swap`, like this:

```ts
export const setIsLoading = (isLoading: boolean) =>
    swap<AppState>(appState, (state): AppState => ({
        ...state,
        foo: 0, // now there's an error
        isLoading,
    }))
```

I'm sure there's a way I could improve the typings for `swap` to make it prevent excess properties more strictly. Don't have the time to mess with it right now, but if anyone wants to PR that feature, I wouldn't be opposed.

However, the excess property should be innocuous. The `Atom`'s type will remain unchanged, so you won't be able to read any excess properties that get put in there. I guess theoretically, this does pose as a sort of memory leak if your app happens to continually add dynamically generated properties to the `Atom`, because they'd never be able to be garbage collected.

**Comment by derrickbeining** [comment]
Going to close this for now, feel free to comment further.

**Comment by soeik** [comment]
Thank you so much for the explanation. Now I see what's happening. And I don't see any way to fix this,  to be honest, unless TS introduces something like the exact type.
